### ISSUE TITLE
is it works as simply serial terminal ?

### ISSUE THREAD

**Issue by ch0mik** [widelec-BB/DeTerm#1]
Hi!
is it works as simply serial terminal - like client for TNC2 modems ?

Regards
Pawel

**Comment by widelec-BB** [comment]
Hi.

I'm sorry, I do not know how I missed notification about this issue.

Version available at the time you opened the issue was not capable of sending anything, so it would be quite useless as a client for any device (but it would be good enough to fetch device output in case that would be helpful during i.e. some diagnostic). Version released today can send data, so it should do the trick, although I'm not familiar with TNC2 modems, so there may be some issue I can't think of.
